
Vagrant.configure("2") do |config|
    config.vm.box = "local/ubuntu-server"
    config.vm.box_url = "~/dev/packer/ubuntu-server/builds/ubuntu-server.box"
    config.vm.boot_timeout = 600

    config.ssh.username = "james"
    config.ssh.insert_key = false
    config.ssh.private_key_path = "~/.ssh/id_rsa"

    config.vm.provider :libvirt do |v|
        v.cpus = 4
        v.memory = 8192
    end
end
