
box_name = "ubuntu-server"
box_path = "~/dev/iac/packer/ubuntu-server"

Vagrant.configure("2") do |config|
    config.vm.box           = "local/#{box_name}"
    config.vm.box_url       = "#{box_path}/builds/#{box_name}.box"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.ssh.username         = "james"
    config.ssh.insert_key       = false
    config.ssh.private_key_path = "#{box_path}/files/id_rsa"

    config.vm.provider :libvirt do |v|
        v.cpus = 4
        v.memory = 8192
    end
end
